# Kubernetes ServiceAccount federated with the id-tofu-controller-storage
# managed identity via Azure AD Workload Identity (no client secret required).
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tofu-controller-storage
  namespace: flux-system
  annotations:
    azure.workload.identity/client-id: "8542c910-9292-4164-97bf-12853a910638"
    azure.workload.identity/tenant-id: "cf36141c-ddd7-45a7-b073-111f66d0b30c"
