# Kubernetes ServiceAccount federated with the id-tofu-controller-storage
# managed identity via Azure AD Workload Identity (no client secret required).
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tofu-controller-storage
  namespace: flux-system
  annotations:
    azure.workload.identity/client-id: "c776fe54-a4bb-49df-b927-eabba61dd6ac"
    azure.workload.identity/tenant-id: "cf36141c-ddd7-45a7-b073-111f66d0b30c"
