# Installs Tofu Controller via Helm, managed by Flux itself.
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  interval: 1h
  url: https://flux-iac.github.io/tofu-controller
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: tofu-controller
      sourceRef:
        kind: HelmRepository
        name: tofu-controller
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
